config/routes.rb
Rails.application.routes.draw do
  root :to => "login#new"
  resources :inquiries do
    member do

    end
  end
  resources :houses
  resources :househunters
  resources :realtors
  resources :companies
  resources :users

  get    '/login',            to: 'login#new'
  post   '/login',            to: 'login#create'
  get    '/logout',           to: 'login#destroy'
  get    '/rel_houses',       to: 'houses#realtorhouses'
  post   '/house_interested', to: 'houses#interested'
  patch   '/house_interested', to: 'houses#interested'
  patch   '/house_not_interested', to: 'houses#not_interested'
  get '/inquiry/new/:id', to: 'inquiries#new', as: :test
  get    '/addimage/:id',  to: 'houses#addimages'
  get '/househunter_inquiries/:id', to: 'inquiries#index', as: :househunter_inquiries
  get     '/input', to: "househunters#input"
  get     '/gotosearch', to:"househunters#search"
  get   '/potential',to: "realtors#potential"
  get    '/admin',            to: 'admin#show', as: :admin
  get     '/edit/admin',      to: 'admin#edit'
  get     '/rswitch',         to: 'realtors#switch'
  get     '/hswitch',         to: 'househunters#switch'
  get     'glogin',           to: redirect('/auth/google_oauth2'), as: 'glogin'
  get     'auth/google_oauth2/callback', to: 'realtors#gcreate', as: 'gcreate'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    session[:previous_url] = request.referer
    @houses = House.all
    @role = session[:role]
    if @role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
    elsif @role == "realtor"
      @realtor = Realtor.find_by(:users_id => session[:user_id])
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    session[:previous_url] = request.referer
    @company_name = Company.find(House.find(params[:id]).companies_id).name
    @houseid = params[:id]
    @role = session[:role]

    if @role =="househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
      @interested_househunter = InterestedHousehunter.find_by(:house_id => params[:id], :househunter_id => @househunter.id)
    elsif @role == "realtor"
      @realtor = Realtor.find_by(:users_id => session[:user_id])
    end

  end

  def realtorhouses
    session[:previous_url] = request.referer
    rel = Realtor.find_by(users_id: session[:user_id])
    if rel.nil? == true || rel.companies_id == nil
      redirect_to session[:previous_url]
    else
      @houses = House.where(realtor_id: rel.id)
      @company = Company.find(rel.companies_id).name
    end
  end

  # GET /houses/new
  def new
    session[:previous_url] = request.referer
    @previous_url = request.referer
    @role = session[:role]
    check_access(@role)
    @realtor = Realtor.find_by(users_id: session[:user_id])

    @house = House.new
    if !session[:is_admin].nil? && session[:is_admin] == true
      @admin = true
      @companies = Company.all
    else
      realtor = Realtor.find_by(users_id: session[:user_id])
      if realtor != nil && realtor.companies_id != nil
        @company = Company.find(realtor.companies_id).name
      else
        redirect_to session[:previous_url], notice: "No company found!"
      end
    end
  end

  # GET /houses/1/edit
  def edit
    session[:previous_url] = request.referer
    @role = session[:role]
    check_access(@role)

    @house = House.find(params[:id])
    if !session[:is_admin].nil? && session[:is_admin] == true
      @admin = true
      @is_listing_creator = true
      @companies = Company.all
    else
      @realtor = Realtor.find_by(users_id: session[:user_id])
      if @realtor.companies_id != nil
        @company = Company.find(@realtor.companies_id).name
      end
    end

    if @role == "realtor"
      if @house.realtor_id != Realtor.find_by(users_id: session[:user_id]).id
        redirect_to houses_path, notice: "You cannot edit listing you have not posted"
      end
    end
    # todo: Delete extra tables in migrations
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    realtor = Realtor.find_by(users_id: session[:user_id])

    if session[:role] != "admin"
      @house.realtor_id = realtor.id
      @house.companies_id = realtor.companies_id
    end
    respond_to do |format|
      if @house.save
        format.html {redirect_to houses_path, notice: 'House was successfully created.'}
        format.json {render :show, status: :created, location: @house}
      else
        format.html {redirect_to houses_path, notice: 'Error saving house'}
        format.json {render json: @house.errors, status: :unprocessable_entity}
      end
    end
  end

  def addimages
    if session[:role] == "realtor"
      realtor = Realtor.find_by(users_id: session[:user_id])
      @house = House.find(params[:id])
      if realtor.companies_id != @house.companies_id
        redirect_to realtor_path(realtor.id), notice: "house does not belong to your company" and return
      end
    elsif session[:role] == "househunter"
      redirect_to househunter_path(realtor.id), notice: "Only realtors can add images" and return
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html {redirect_to @house, notice: 'House was successfully updated.'}
        format.json {render :show, status: :ok, location: @house}
      else
        format.html {render :edit}
        format.json {render json: @house.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    if session[:role] != "admin"
      realtor = Realtor.find_by(users_id: session[:user_id])
      if realtor == nil || @house.realtor_id != realtor.id
        redirect_to houses_path, notice: "You cannot delete listing you have not posted"
      end
    end
    @house.destroy
    respond_to do |format|
      format.html {redirect_to houses_url, notice: 'House was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def interested
    @househunter = Househunter.find_by(users_id: session[:user_id])
    @interested_househunter = InterestedHousehunter.find_by(:house_id => params[:id], :househunter_id => @househunter.id)

    respond_to do |format|
      if @interested_househunter
        format.html {redirect_to request.referer, notice: 'Already present in the interest list!'}
      else
        @interested_househunter = InterestedHousehunter.new(house_id: params[:id], househunter_id: @househunter.id)
        if @interested_househunter.save
          format.html {redirect_to request.referer, notice: 'Successful!'}
        else
          format.html {redirect_to request.referer, flash: {error: 'Error'}}
        end
      end
    end

  end

  def not_interested
    @househunter = Househunter.find_by(users_id: session[:user_id])
    @interested_househunter = InterestedHousehunter.find_by(:house_id => params[:id], :househunter_id => @househunter.id)

    respond_to do |format|
      if @interested_househunter.destroy
        format.html {redirect_to request.referer, notice: 'Successfully removed house from the interest list!'}
      else
        format.html {redirect_to request.referer, flash: {error: 'Error'}}
      end
    end
  end

  def check_access(role)
    if role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
      redirect_to househunter_path(@househunter), notice: "You are not allowed to access that url"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_house
    @house = House.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def house_params
    params.require(:house).permit(:realtor_id, :companies_id, :location, :area, :year_built, :style, :list_prize, :floor_count, :basement, :owner_name, images: [])
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.label :year_built %>
    <%= form.number_field :year_built %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :list_prize %>
    <%= form.number_field :list_prize %>
  </div>

  <div class="field">
    <%= form.label :floor_count %>
    <%= form.number_field :floor_count %>
  </div>

  <div class="field">
    <%= form.label :basement %>
    <%= form.check_box :basement %>
  </div>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_field :owner_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/addimages.html.erb
<%= form_for @house do |f| %>
Add MORE images: <br><%= f.file_field :images, multiple: true %><br><br>
  <%= f.submit "Add images" %><br><br>
<% end %>
<%= link_to 'Back', @previous_url %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= form_for @house do |f| %>

  Company:
  <% if @role == 'admin' %>
    <% options = options_from_collection_for_select(@companies, 'id', 'name') %>
    <%= f.select "companies_id", options %><br>
  <% else %>
    <%= @company %><br>
  <% end %>
  <%= f.label :location %>
  <%= f.text_area :location %>
  <%= f.label :area %>
  <%= f.text_field :area %>
  <%= f.label :year_built %>
  <%= f.number_field :year_built %>
  <%= f.label :style %>
  <%= f.text_field :style %>
  <%= f.label :list_prize %>
  <%= f.number_field :list_prize %><br>
  <%= f.label :floor_count %>
  <%= f.number_field :floor_count %><br>
  <%= f.label :owner_name %>
  <%= f.text_field :owner_name %><br>
  Basement:  <%= f.check_box :basement %><br>
  Add MORE images: <br><%= f.file_field :images, multiple: true %><br><br>
  <%= f.submit "Update House" %>
<% end %>


<%= link_to 'Show', @house %>

<%= link_to 'Back', @previous_url %>


<% if @role == 'admin' %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == 'realtor' %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor) %> <br>
<% end %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>
<%= link_to 'search', input_path %>

<table cellspacing="10">
  <thead>
  <tr>
    <th>Company</th>
    <th>Location</th>
    <th>Area</th>
    <th>Year built</th>
    <th>Style</th>
    <th>List prize</th>
    <th>Floor count</th>
    <th>Basement</th>
    <th>Owner name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @houses.each do |house| %>
    <tr>
      <td><%= house.companies_id %></td>
      <td><%= house.location %></td>
      <td><%= house.area %></td>
      <td><%= house.year_built %></td>
      <td><%= house.style %></td>
      <td><%= house.list_prize %></td>
      <td><%= house.floor_count %></td>
      <td><%= house.basement %></td>
      <td><%= house.owner_name %></td>
      <td><%= link_to 'Show', house %></td>
      <% if @role == "admin" %>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= button_to 'Destroy', house, method: :delete, :onclick => "return confirm('Are you sure you want to delete this house?')" %>
        </td>
      <% end %>
      <% if @role == "admin" || @role=="realtor" %>
        <td><%= link_to 'Add image', "/addimage/#{house.id}" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if @role == 'admin'  %>
  <%= link_to 'New House', new_house_path %>
<% end %>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "realtor" %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor.id) %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', househunter_path(@househunter.id) %> <br>
<% end %>

app/views/houses/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New House</h1>

<%= form_for @house do |f| %>
  Company:
  <% if @admin == true %>
    <% options = options_from_collection_for_select(@companies, 'id', 'name') %>
    <%= f.select "companies_id", options %><br>
  <% else %>
    <%= @company %><br>
  <% end %>
  <%= f.label :location %>
  <%= f.text_area :location %>
  <%= f.label :area %>
  <%= f.text_field :area %>
  <%= f.label :year_built %>
  <%= f.number_field :year_built %>
  <%= f.label :style %>
  <%= f.text_field :style %>
  <%= f.label :list_prize %>
  <%= f.number_field :list_prize %><br>
  <%= f.label :floor_count %>
  <%= f.number_field :floor_count %><br>
  <%= f.label :owner_name %>
  <%= f.text_field :owner_name %><br>
  Basement:  <%= f.check_box :basement %><br>
  Add images: <br><%= f.file_field :images, multiple: true %><br><br>

  <%= f.submit "Create House" %><br><br>
<% end %>



<%= link_to 'Back', @previous_url %>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "realtor" %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor) %> <br>
<% end %>

app/views/houses/realtorhouses.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
  <tr>
    <th>Company</th>
    <th>Location</th>
    <th>Area</th>
    <th>Year built</th>
    <th>Style</th>
    <th>List prize</th>
    <th>Floor count</th>
    <th>Basement</th>
    <th>Owner name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @houses.each do |house| %>
    <tr>
      <td><%= @company %></td>
      <td><%= house.location %></td>
      <td><%= house.area %></td>
      <td><%= house.year_built %></td>
      <td><%= house.style %></td>
      <td><%= house.list_prize %></td>
      <td><%= house.floor_count %></td>
      <td><%= house.basement %></td>
      <td><%= house.owner_name %></td>
      <td><%= link_to 'Show', house %></td>
      <td><%= link_to 'Edit', edit_house_path(house) %></td>
      <td><%= button_to 'Destroy', house, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>
<%= link_to 'Back', @previous_url %>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "realtor" %>
  <%= link_to 'Back to Dashboard', realtor_path(rel.id) %> <br>
<% end %>

app/views/houses/show.html.erb
<h1>House Details:</h1>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @company_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p>
  <strong>Area:</strong>
  <%= @house.area %>
</p>

<p>
  <strong>Year built:</strong>
  <%= @house.year_built %>
</p>

<p>
  <strong>Style:</strong>
  <%= @house.style %>
</p>

<p>
  <strong>List prize:</strong>
  <%= @house.list_prize %>
</p>

<p>
  <strong>Floor count:</strong>
  <%= @house.floor_count %>
</p>

<p>
  <strong>Basement:</strong>
  <%= @house.basement %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @house.owner_name %>
</p>
<% if @role == "househunter" %>

  <% if @interested_househunter == nil%>
    <%= form_for @househunter, url: '/house_interested' do |f| %>
      <input type="hidden" id="id" name="id" value="<%= @houseid %>"/>
      <%= f.submit "Interested in this house" %><br>
    <% end %>

  <% else %>
    <%= form_for @househunter, url: '/house_not_interested' do |f| %>
      <input type="hidden" id="id" name="id" value="<%= @houseid %>"/>
      <%= f.submit "Not Interested in this house" %><br>
    <% end %>
  <% end %>

  <br>
  <%= link_to 'Submit an enquiry', test_path(@houseid) %>

<% end %>

<% if @role != "househunter" %>
  <%= link_to 'Edit', edit_house_path(@house) %><br>
<% end %>

<br>
<%= link_to 'Back', @previous_url %>
<br>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "househunter" %>
  <%= link_to 'Back to Dashboard', househunter_path(@househunter.id) %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor.id) %> <br>
<% end %>

<% @house.images.each do |image| %>
  <%= image_tag image %> <br/>
<% end %>