config/routes.rb
Rails.application.routes.draw do
  root :to => "login#new"
  resources :inquiries do
    member do

    end
  end
  resources :houses
  resources :househunters
  resources :realtors
  resources :companies
  resources :users

  get    '/login',            to: 'login#new'
  post   '/login',            to: 'login#create'
  get    '/logout',           to: 'login#destroy'
  get    '/rel_houses',       to: 'houses#realtorhouses'
  post   '/house_interested', to: 'houses#interested'
  patch   '/house_interested', to: 'houses#interested'
  patch   '/house_not_interested', to: 'houses#not_interested'
  get '/inquiry/new/:id', to: 'inquiries#new', as: :test
  get    '/addimage/:id',  to: 'houses#addimages'
  get '/househunter_inquiries/:id', to: 'inquiries#index', as: :househunter_inquiries
  get     '/input', to: "househunters#input"
  get     '/gotosearch', to:"househunters#search"
  get   '/potential',to: "realtors#potential"
  get    '/admin',            to: 'admin#show', as: :admin
  get     '/edit/admin',      to: 'admin#edit'
  get     '/rswitch',         to: 'realtors#switch'
  get     '/hswitch',         to: 'househunters#switch'
  get     'glogin',           to: redirect('/auth/google_oauth2'), as: 'glogin'
  get     'auth/google_oauth2/callback', to: 'realtors#gcreate', as: 'gcreate'
end

app/views/admin/edit.html.erb
<%= form_for @admin do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :email_id %>
  <%= f.label :last_name %>
  <%= f.text_field :password %><br><br>
  <%= f.submit "Update Fields" %>
<% end %>

app/views/admin/show.html.erb
<h1>Admin Dashboard</h1>

Welcome, <%=  "#{@admin.email_id} #{@admin.password}" %><br><br>

<%= link_to 'Edit Profile', edit_admin_path  %><br>
<br>
<h2>Realtor:</h2>
<%= link_to 'Create Realtor', new_realtor_path %><br>
<%= link_to 'View or modify realtors', realtors_path %><br>
<br>
<h2>House Hunter:</h2>
<%= link_to 'Create Househunter', new_househunter_path %><br>
<%= link_to 'View or modify househunters', househunters_path %><br>
<br>
<h2>Realestate Company: </h2>
<%= link_to 'Create realestate company', new_company_path %><br>
<%= link_to 'View or modify realestate companies', companies_path %><br>
<br>
<h2>Users:</h2>
<%= link_to 'View or modify Users', users_path %><br>
<br>
<h2>Houses:</h2>
<%= link_to 'View or modify houses', houses_path %><br>
<br>
<h2>Inquiries:</h2>
<%= link_to 'View or modify inquiries', inquiries_path %><br>
<br>
<%= link_to 'Logout', logout_path %><br>