config/routes.rb
Rails.application.routes.draw do
  root :to => "login#new"
  resources :inquiries do
    member do

    end
  end
  resources :houses
  resources :househunters
  resources :realtors
  resources :companies
  resources :users

  get    '/login',            to: 'login#new'
  post   '/login',            to: 'login#create'
  get    '/logout',           to: 'login#destroy'
  get    '/rel_houses',       to: 'houses#realtorhouses'
  post   '/house_interested', to: 'houses#interested'
  patch   '/house_interested', to: 'houses#interested'
  patch   '/house_not_interested', to: 'houses#not_interested'
  get '/inquiry/new/:id', to: 'inquiries#new', as: :test
  get    '/addimage/:id',  to: 'houses#addimages'
  get '/househunter_inquiries/:id', to: 'inquiries#index', as: :househunter_inquiries
  get     '/input', to: "househunters#input"
  get     '/gotosearch', to:"househunters#search"
  get   '/potential',to: "realtors#potential"
  get    '/admin',            to: 'admin#show', as: :admin
  get     '/edit/admin',      to: 'admin#edit'
  get     '/rswitch',         to: 'realtors#switch'
  get     '/hswitch',         to: 'househunters#switch'
  get     'glogin',           to: redirect('/auth/google_oauth2'), as: 'glogin'
  get     'auth/google_oauth2/callback', to: 'realtors#gcreate', as: 'gcreate'
end

app/models/realtor.rb
class Realtor < ApplicationRecord
  has_many :houses
end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  before_action :set_realtor, only: [:show, :edit, :update, :destroy]

  # GET /realtors
  # GET /realtors.json
  def index
    @role = session[:role]
    check_access(@role)
    if session[:role] != "admin"
      redirect_to login_path, notice: "You cannot access the page"
    end
    @realtors = Realtor.all
  end

  # GET /realtors/1
  # GET /realtors/1.json
  def show
    @role = session[:role]
    check_access(@role)
    # Show company name if realtor belongs to company
    @realtor = Realtor.find(params[:id])
    if @realtor.companies_id != nil
      @company = Company.find(@realtor.companies_id)
    end
    if session[:role] == 'admin'
      redirect_to login_path
    else
      user = User.find(session[:user_id])
      if user.is_househunter == true
        @switchable = true
      end
    end
  end

  # GET /realtors/new
  def new
    @role = session[:role]
    check_access(@role)
    @realtor = Realtor.new
  end

  # GET /realtors/1/edit
  def edit
    @role = session[:role]
    check_access(@role)
    @realtor = Realtor.find(params[:id])
    @companies = Company.all # To populate dropdown
    if @realtor.companies_id != nil
      @company = @realtor.companies_id
    end
  end

  # POST /realtors
  # POST /realtors.json
  def create
    existing_user = User.find_by(email_id: params[:user][:email_id])
    if existing_user != nil
      if existing_user.is_realtor == true
        redirect_to login_path, notice: 'You are already registered as an Realtor'
      else
        existing_user.is_realtor = true
        existing_user.password = params[:user][:password]
        if existing_user.save
          add_realtor = Realtor.new(realtor_params)
          add_realtor.users_id = existing_user.id
          if add_realtor.save
            redirect_to login_path, notice: 'Realtor was successfully created.'
          else
            redirect_to login_path, notice: 'Error saving realtor.'
          end
        else
          redirect_to login_path, notice: 'Error saving user.'
        end
      end
    else
      @realtor = Realtor.new(realtor_params)
      @user = User.new(user_params)
      @user.is_realtor = true
      respond_to do |format|
        if @user.save
          @realtor.users_id = @user.id
          if @realtor.save
            format.html {redirect_to login_path, notice: 'Realtor was successfully created.'}
            format.json {render :show, status: :created, location: @realtor}
          else
            format.html {redirect_to login_path, notice: 'Error creating realtor'}
            format.json {render json: @realtor.errors, status: :unprocessable_entity}
          end
        else
          format.html {redirect_to login_path, notice: 'Error creating user. Please check input.'}
          format.json {render json: @user.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  def potential
    rel = Realtor.find_by(users_id: session[:user_id])
    @potential = InterestedHousehunter.select('h.id','hh.first_name','hh.last_name').joins("inner join houses h on h.id = house_id inner join househunters hh on hh.id = househunter_id").where("h.companies_id=#{rel.companies_id}")

    #session[:previous_url] = request.referer
    # rel = Realtor.find_by(users_id: session[:user_id])
    # puts rel.id
    # @com = Company.find(rel.companies_id)
    # @house = House.where(:companies_id => @com.id)
    # #hh = Hash.new
    # fh = Hash.new
    # @fu = Hash.new
    # i = 0
    # j = 0
    # puts @house
    # @house.each do |h|
    #
    #   hh = InterestedHousehunter.where(:house_id => h[:id])
    #   unless hh.empty?
    #     @fu[i] = Househunter.where(:id => hh[0][:househunter_id])
    #     i = i + 1
    #   end
    #   #fh[i]={h.id=>h,hh[h.id][:househunter_id]=>fu[hh[h.id][:househunter_id]]}
    #   #i=i+1
    # end
    # #@househunters=Househunter.find_by()
  end

  # PATCH/PUT /realtors/1
  # PATCH/PUT /realtors/1.json
  def update
    prev_company = @realtor.companies_id
    respond_to do |format|
      if @realtor.update(realtor_params)
        if @realtor.companies_id != prev_company
          House.where(companies_id: prev_company).destroy_all
        end
        if params[:user][:password] != nil && params[:user][:password] != ""
          if User.find(session[:user_id]).update(password: params[:user][:password])
            reset_session
            redirect_to login_path, notice: 'Password successfully changed' and return
          else
            redirect_to @realtor, notice: 'Error changing password'
          end
        end
        format.html {redirect_to @realtor, notice: 'Realtor was successfully updated.'}
        format.json {render :show, status: :ok, location: @realtor}
      else
        format.html {render :edit}
        format.json {render json: @realtor.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /realtors/1consist
  # DELETE /realtors/1.json
  def destroy
    @user = User.find_by(:id => @realtor.users_id)
    if @user.is_admin != true && @user.is_househunter != true
      @user.destroy
    else
      @user.is_realtor = 0
      @user.save
    end
    @realtor.destroy

    respond_to do |format|
      format.html {redirect_to realtors_url, notice: 'Realtor was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def check_access(role)
    if role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
      redirect_to househunter_path(@househunter), notice: "You are not allowed to access that url"
    end
  end

  def switch
    session[:role] = 'househunter'
    redirect_to login_path
  end

  def gcreate
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:role] = 'realtor'
    session[:user_id] = @user.id
    session[:is_realtor] = true
    session[:logged_in] = true
    redirect_to login_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_realtor
    @realtor = Realtor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def realtor_params
    params.require(:realtor).permit(:first_name, :last_name, :companies_id, :phone_number, :user_id)
  end

  #Allows saving of user from within realtors controller.
  def user_params
    params.require(:user).permit(:email_id, :password, :is_admin, :is_realtor, :is_househunter)
  end

end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/realtors/_form.html.erb
<%= form_with(model: realtor, local: true) do |form| %>
  <% if realtor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(realtor.errors.count, "error") %> prohibited this realtor from being saved:</h2>

      <ul>
      <% realtor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/realtors/edit.html.erb
<h1>Editing Realtor</h1>

<%= form_for @realtor do |f| %>
  Company<br>
  <% options = options_from_collection_for_select(@companies, 'id', 'name') %>
  <%= f.select "companies_id", options %><br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %><br>
  Change password (Leave blank to keep the same)<br><input type="password" name="user[password]" id="user_password" /><br><br>
  <%= f.submit "Update Fields" %><br><br>
<% end %>

<%= link_to 'Show', @realtor %> <br>
<%= link_to 'Create a new company', new_company_path %>  <br>
<% if @company != nil %>
  <%= link_to 'Edit your company', edit_company_path(@company) %> <br>
<% end %>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor.id) %> <br>
<% end %>

app/views/realtors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Realtors</h1>

<table cellspacing="10">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @realtors.each do |realtor| %>
      <tr>
        <td><%= realtor.first_name %></td>
        <td><%= realtor.last_name %></td>
        <td><%= realtor.companies_id %></td>
        <td><%= realtor.phone_number %></td>
        <td><%= link_to 'Show', realtor %></td>
        <td><%= link_to 'Edit', edit_realtor_path(realtor) %></td>
        <td><%= button_to 'Destroy', realtor, method: :delete, :onclick => "return confirm('Are you sure you want to delete this realtor?')" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Realtor', new_realtor_path %>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>

app/views/realtors/new.html.erb
<h1>New Realtor</h1>

<p id="notice"><%= notice %></p>

<%= form_for @realtor do |f| %>
  First Name<br><%= f.text_field :first_name %><br>
  Last Name<br><%= f.text_field :last_name %><br>
  Email<br><input type="email" name="user[email_id]" id="user_email_id" /><br>
  Password<br><input type="password" name="user[password]" id="user_password" /><br>
  <%= f.submit "Sign up" %><br>
<% end %>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>

app/views/realtors/potential.html.erb
<h1>Potential buyers</h1>

<table>
  <thead>
  <tr>
    <th>House</th>
    <th>First name</th>
    <th>Last name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>

  <%# @fu.each do |k,v| %>
    <%# v.each do |f| %>
<!--      <tr>-->
<!--        <td><%#=f.first_name %></td>-->
<!--        <td><%#=f.last_name %></td>-->
<!--      </tr>-->
    <%#end %>
  <%# end %>

  <% @potential.each do |potential| %>
    <tr>
      <td><%= link_to 'Show house', house_path(potential.id) %></td>
      <td><%= potential.first_name %></td>
      <td><%= potential.last_name %></td>
    </tr>
  <% end %>


  </tbody>
</table>
<%= link_to 'Back ', "/realtors/#{params[:id]}" %> <br>
<br>

app/views/realtors/show.html.erb
<h1>Realtor Dashboard</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @realtor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @realtor.last_name %>
</p>

<p>
  <strong>Company:</strong>
  <% if @company != nil %>
    <%= @company.name %>
  <% end %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @realtor.phone_number %>
</p>

<% if @role == "realtor" %>
  <%= link_to 'Edit profile and company', edit_realtor_path(@realtor) %> <br>
  <br><h2> Houses </h2>
  <%= link_to 'List new House', new_house_path %><br>
  <%= link_to 'View and Edit houses listed by you', rel_houses_path %><br>
  <%= link_to 'View all listed houses', houses_path %><br>
  <h2> Buyers </h2>
  <%= link_to 'View list of potential buyers', potential_path %><br>
  <%= link_to 'View list of all inquiries', inquiries_path %><br>
<% end %><br>
<%= link_to 'Logout', logout_path %>

<br>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>

<br>
<% if @switchable == true %>
  <%= link_to "Switch to House Hunter's profile", "/rswitch"%> <br>
<% end %>