config/routes.rb
Rails.application.routes.draw do
  root :to => "login#new"
  resources :inquiries do
    member do

    end
  end
  resources :houses
  resources :househunters
  resources :realtors
  resources :companies
  resources :users

  get    '/login',            to: 'login#new'
  post   '/login',            to: 'login#create'
  get    '/logout',           to: 'login#destroy'
  get    '/rel_houses',       to: 'houses#realtorhouses'
  post   '/house_interested', to: 'houses#interested'
  patch   '/house_interested', to: 'houses#interested'
  patch   '/house_not_interested', to: 'houses#not_interested'
  get '/inquiry/new/:id', to: 'inquiries#new', as: :test
  get    '/addimage/:id',  to: 'houses#addimages'
  get '/househunter_inquiries/:id', to: 'inquiries#index', as: :househunter_inquiries
  get     '/input', to: "househunters#input"
  get     '/gotosearch', to:"househunters#search"
  get   '/potential',to: "realtors#potential"
  get    '/admin',            to: 'admin#show', as: :admin
  get     '/edit/admin',      to: 'admin#edit'
  get     '/rswitch',         to: 'realtors#switch'
  get     '/hswitch',         to: 'househunters#switch'
  get     'glogin',           to: redirect('/auth/google_oauth2'), as: 'glogin'
  get     'auth/google_oauth2/callback', to: 'realtors#gcreate', as: 'gcreate'
end

app/models/househunter.rb
class Househunter < ApplicationRecord
end

app/controllers/househunters_controller.rb
class HousehuntersController < ApplicationController
  before_action :set_househunter, only: [:show, :edit, :update, :destroy]

  # GET /househunters
  # GET /househunters.json
  def index
    @role = session[:role]
    @househunters = Househunter.all
    if session[:role] != "admin"
      redirect_to login_path, notice: "You are not allowed to access that url"
    end
  end

  # GET /househunters/1
  # GET /househunters/1.json
  def show

    @user = User.find(@househunter.users_id)
    #UserMailer.welcome_email.deliver_now
    @role = session[:role]
    check_access(@role)
    if @role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
    end
    user = User.find(session[:user_id])
    if user.is_realtor == true
      @switchable = true
    end
  end

  # GET /househunters/new
  def new
    @role = session[:role]
    check_access(@role)
    @househunter = Househunter.new
  end

  # GET /househunters/1/edit
  def edit
    @role = session[:role]
    check_access(@role)
    @househunter = Househunter.find(params[:id])
  end

  # POST /househunters
  # POST /househunters.json
  def create
    existing_user = User.find_by(email_id: params[:user][:email_id])
    if existing_user != nil
      if existing_user.is_househunter == true
        redirect_to logout_path, notice: "You are already registered as a house hunter"
      else
        existing_user.is_househunter = true
        existing_user.password = params[:user][:password]
        if existing_user.save
          add_hh = Househunter.new(househunter_params)
          add_hh.users_id = existing_user.id
          if add_hh.save
            redirect_to login_path, notice: 'House hunter was successfully created'
          else
            redirect_to login_path, notice: 'Error saving househunter'
          end
        else
          redirect_to login_path, notice: 'Error saving user.'
        end
      end
    else
      @househunter = Househunter.new(househunter_params)
      @user = User.new(user_params)
      @user.is_househunter = true
      respond_to do |format|
        if @user.save
          @househunter.users_id = @user.id
          if @househunter.save
            format.html {redirect_to login_path, notice: 'House hunter was successfully created.'}
            format.json {render :show, status: :created, location: @househunter}
          else
            format.html {render :new}
            format.json {render json: @realtor.errors, status: :unprocessable_entity}
          end
        else
          format.html {render :new}
          format.json {render json: @user.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  # PATCH/PUT /househunters/1
  # PATCH/PUT /househunters/1.json
  def update
    respond_to do |format|
      if @househunter.update(househunter_params)
        if params[:user][:password] != nil && params[:user][:password] != ""
          if User.find(session[:user_id]).update(password: params[:user][:password])
            reset_session
            redirect_to login_path, notice: 'Password successfully changed' and return
          else
            redirect_to @househunter, notice: 'Error changing password'
          end
        end
        format.html {redirect_to @househunter, notice: 'Househunter was successfully updated.'}
        format.json {render :show, status: :ok, location: @househunter}
      else
        format.html {render :edit}
        format.json {render json: @househunter.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /househunters/1
  # DELETE /househunters/1.json
  def destroy
    @user = User.find_by(:id => @househunter.users_id)
    @househunter.destroy()
    if @user.is_admin != true && @user.is_realtor != true
      @user.destroy
    else
      @user.is_househunter = 0
      @user.save
    end
    respond_to do |format|
      format.html {redirect_to househunters_url, notice: 'Househunter was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def input
    @previous_url = request.referrer
    @role = session[:role]
    if @role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
    else
      @realtor = Realtor.find_by(:users_id => session[:user_id])
    end
  end

  def search
    @role = session[:role]
    if @role == "househunter"
      @househunter = Househunter.find_by(:users_id => session[:user_id])
    else
      @realtor = Realtor.find_by(:users_id => session[:user_id])
    end


    str = ""
    if params[:location] != nil && params[:location] != ""
      if str.empty?
        str = str + " location = '#{params[:location]}'"
      else
        str = str + "AND location = '#{params[:location]}' "
      end
    end
    if (params[:year_built1]== nil || params[:year_built1]== "" )&& ( params[:year_built2]==nil || params[:year_built2]=="")
      str=str+""
    else
      if params[:year_built1] == nil || params[:year_built1] == ""
        miny=0
      else
        miny=params[:year_built1]
      end
      if params[:year_built2] == nil || params[:year_built2] == ""
        maxy=99999
      else
        maxy=params[:year_built2]
      end
      if str.empty?
        str = str + " year_built > #{miny} AND year_built < #{maxy} "
      else
        str = str + " AND year_built > #{miny} AND year_built < #{maxy} "
      end
    end

    if params[:style] != nil && params[:style] != ""
      if str.empty?
        str = str + " style = '#{params[:style]}' "
      else
        str = str + " AND style = '#{params[:style]}' "
      end
    end
    if (params[:list_prize1]==nil || params[:list_prize1]=="" )&&  (params[:list_prize2]==nil || params[:list_prize2]=="")
      str=str+""
    else
      if params[:list_prize1] == nil || params[:list_prize1] == ""
        minl=0
      else
        minl=params[:list_prize1]
      end
      if params[:list_prize2] == nil || params[:list_prize2] == ""
        maxl=99999
      else
        maxl=params[:list_prize2]
      end
      if str.empty?
        str = str + " list_prize > #{minl} AND list_prize < #{maxl} "
      else
        str = str + " AND list_prize => #{minl} AND list_prize < #{maxl} "
      end
    end

    if (params[:floor_count1]==nil || params[:floor_count1]=="") &&  (params[:floor_count2]==nil || params[:floor_count2]=="")
      str=str+""
    else
      if params[:floor_count1] == nil || params[:floor_count1] == ""
        minf=0
      else
        minf=params[:floor_count1]
      end
      if params[:floor_count2] == nil || params[:floor_count2] == ""
        maxf=99999
      else
        maxf=params[:area2]
      end
      if str.empty?
        str = str + " floor_count > #{minf} AND floor_count < #{maxf} "
      else
        str = str + " AND floor_count > #{minf} AND floor_count < #{maxf} "
      end
    end
    if params[:basement] != nil && params[:basement] != ""
      if str.empty?
        str = str + " basement=#{params[:basement]} "
      else
        str = str + " AND basement=#{params[:basement]} "
      end
    end
    if params[:owner_name] != nil && params[:owner_name] != ""
      if str.empty?
        str = str + " owner_name='#{params[:owner_name]}' "
      else
        str = str + " AND owner_name='#{params[:owner_name]}' "
      end
    end

      @houses =House.where(str)
  end

  def check_access(role)
    if role == "realtor"
      @realtor = Realtor.find_by(:users_id => session[:user_id])
      redirect_to realtor_path(@realtor), notice: "You are not allowed to access that url"
    end
  end

  def switch
    session[:role] = 'realtor'
    redirect_to login_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_househunter
    @househunter = Househunter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def househunter_params
    params.require(:househunter).permit(:first_name, :last_name, :phone, :contact_method, :users_id)
  end

  def user_params
    params.require(:user).permit(:email_id, :password, :is_admin, :is_realtor, :is_househunter)
  end
end

app/helpers/househunters_helper.rb
module HousehuntersHelper
end

app/views/househunters/_form.html.erb
<%= form_with(model: househunter, local: true) do |form| %>
  <% if househunter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(househunter.errors.count, "error") %> prohibited this househunter from being saved:</h2>

      <ul>
        <% househunter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :contact_method %>
    <%= form.text_field :contact_method %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/househunters/edit.html.erb
<h1>Editing Househunter</h1>

<%= form_for @househunter do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :phone %>
  <%= f.number_field :phone %>
  <%= f.label :contact_method %>
  <%= f.number_field :contact_method %><br>
  Change password (Leave blank to keep the same)<br><input type="password" name="user[password]" id="user_password" /><br><br>
  <%= f.submit "Update Fields" %><br><br>
<% end %>

<br>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', househunter_path(@househunter.id) %> <br>
<% end %>

app/views/househunters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Househunters</h1>

<table cellspacing="10">
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone</th>
    <th>Contact method</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @househunters.each do |househunter| %>
    <tr>
      <td><%= househunter.first_name %></td>
      <td><%= househunter.last_name %></td>
      <td><%= househunter.phone %></td>
      <td><%= househunter.contact_method %></td>
      <td><%= link_to 'Show', househunter %></td>
      <td><%= link_to 'Edit', edit_househunter_path(househunter) %></td>
      <td><%= button_to 'Destroy', househunter, method: :delete, :onclick => "return confirm('Are you sure you want to delete this househunter?')" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Househunter', new_househunter_path %>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>

app/views/househunters/input.html.erb
<h1>Search Houses</h1>
<p id="notice"><%= notice %></p>
<%=form_tag(gotosearch_path, :method => "get") do %>
  <%= label_tag(:location, "location:") %>
  <%= text_field_tag(:location) %><br>
  <%= label_tag(:year_built1, "min year:") %>
  <%= text_field_tag(:year_built1)%><br>
  <%= label_tag(:year_built2, " max year:") %>
  <%= text_field_tag(:year_built2)%><br>
  <%= label_tag(:style, "style:") %>
  <%= text_field_tag(:style) %><br>
  <%= label_tag(:list_prize1, " min list prize:") %>
  <%= text_field_tag(:list_prize1) %><br>
  <%= label_tag(:list_prize2, " max list prize:") %>
  <%= text_field_tag(:list_prize2) %><br>
  <%= label_tag(:floor_count1, "min floor count") %>
  <%= text_field_tag(:floor_count1) %><br>
  <%= label_tag(:floor_count2, "max floor count") %>
  <%= text_field_tag(:floor_count2) %><br>
  <%= label_tag(:basement, "basement enter value as true or false:") %>
  <%= text_field_tag(:basement) %><br>
  <%= label_tag(:owner_name, "owner name") %>
  <%= text_field_tag(:owner_name) %><br>

  <%= submit_tag("Search") %>
<% end %>

<br>
<%= link_to 'Back', @previous_url %>
<br>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "househunter" %>
  <%= link_to 'Back to Dashboard', househunter_path(@househunter.id) %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor.id) %> <br>
<% end %>

app/views/househunters/new.html.erb
<h1>New Househunter</h1>

<%= form_for @househunter do |f| %>
  First Name<br><%= f.text_field :first_name %><br>
  Last Name<br><%= f.text_field :last_name %><br>
  Email<br><input type="email" name="user[email_id]" id="user_email_id" /><br>
  Password<br><input type="password" name="user[password]" id="user_password" /><br>
  <%= f.submit "Sign up" %><br>
<% end %>

<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>

app/views/househunters/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <tbody>
  <% @houses.each do |house| %>
    <%if !house.nil? %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.area %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.list_prize %></td>
        <td><%= house.floor_count %></td>
        <td><%= house.basement %></td>
        <td><%= house.owner_name %></td>
        <td><%= house.owner_name %></td>
      </tr>
    <%end %>
  <% end %>
  </tbody>
</table>


<br>
<%= link_to 'Back', @previous_url %>
<br>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% elsif @role == "househunter" %>
  <%= link_to 'Back to Dashboard', househunter_path(@househunter.id) %> <br>
<% else %>
  <%= link_to 'Back to Dashboard', realtor_path(@realtor.id) %> <br>
<% end %>

app/views/househunters/show.html.erb
<h1>Househunter Dashboard</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @househunter.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @househunter.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @househunter.phone %>
</p>

<p>
  <strong>Contact method:</strong>
  <%= @househunter.contact_method %>
</p>

<% if @role == "househunter" %>
  <%= link_to 'Edit Profile', edit_househunter_path(@househunter) %>
  <br>
  <%= link_to 'Show Houses', houses_path %>
  <br>
  <%= link_to 'Show Real estate companies', companies_path %>
  <br>
  <%= link_to 'Show Inquiries', househunter_inquiries_path(@househunter) %>

  <br>
  <%= link_to 'Search Houses', input_path %><br>
<% end %>
<br>
<% if @role == "admin" %>
  <%= link_to 'Back to Dashboard', admin_path %> <br>
<% end %>
<br>
<% if @switchable == true %>
  <%= link_to "Switch to Realtor's profile", "/hswitch"%> <br>
<% end %>

<br>
<%= link_to 'Logout', logout_path %><br>